### ISSUE TITLE
The initial code needs fixing

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-mdl-bridge#1]
The code in this repository is a copy of the upgraded code in **[skeleton-bridge](https://github.com/aurelia-ui-toolkits/skeleton-bridge)**, where upgraded means that I just added parts of the [KendoUI bridge](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge) that were added after the last changes in skeleton-bridge]. 

Please fix - and apply the same fix to **[skeleton-bridge](https://github.com/aurelia-ui-toolkits/skeleton-bridge)**

`gulp-watch` results with

```
λ gulp watch
module.js:340
    throw err;
    ^

Error: Cannot find module 'gulp-sourcemaps'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\work\aurelia-ui-toolkits\MDL\aurelia-mdl-bridge\build\tasks\build.js:13:18)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
```

**Comment by Thanood** [comment]
`gulp-sourcemaps` was referenced in `jspm.dependencies` instead of `npm.devDependencies`. Also `gulp-coveralls` was missing. There have been some jspm forks which are resolved now.

Also, `font-awesome` is now loaded by SystemJS so you don't have to update the `<link>` in `index.html` after every update. :smile: 

I will apply these changes to `skeleton-bridge` today.
